### PR TITLE
Fix JSON decode and empty post_date

### LINKED ISSUE #185: GitHub import to Wordpress publishes incorrect date and doesn't auto import after commit
GitHub import to Wordpress publishes incorrect date and doesn't auto import after commit
(Using Wordpress v. 4.8)

**Issues with GitHub > Wordpress Import**

1. When committing a new file, the file doesn't export to Wordpress until I click the "Import from GitHub" link in WordPress (from my understanding, the expectation is that it should auto-import as long as a commit is made whether it's an existing or new published post).
2. When creating a new .md file in GitHub, I leave the date blank in YAML header, and for some reason, the date published in Wordpress will date it as 1970-01-01 rather than real-time date.

### PR DESCRIPTION
**Pull request by JayWood**
This fixes #185 

Two issues here.

When the payload comes from GitHub you have to `parse_str` on the raw data and then access the `payload` key, that is what retains the JSON.  However, in the interest of backwards compatibility I left the same old method there, but only ran the new method if it failed.

As for the date - it was due to the `post_date` being empty prior to being passed to `get_gmt_from_date` so now if it's empty, but is still set, we will now use `current_time()` to get the WordPress time during import, and no longer pass an empty string to the GMT function.

### CODE REVIEW

**Comment by JayWood** [comment]
Also, noticed I referenced issue 85, not 185 😄 I'm not perfect haha

File: lib/import.php [hunk 1]
```diff
@@ -188,6 +188,11 @@ protected function blob_to_post( WordPress_GitHub_Sync_Blob $blob ) {
 
 			if ( array_key_exists( 'post_date', $meta ) ) {
 				$args['post_date'] = $meta['post_date'];
+
+				if ( empty( $meta['post_date'] ) ) {
+					$meta['post_date'] = current_time( 'mysql' );
+				}
```
Comment (mAAdhaTTah) [inline lib/import.php]: I think this block should go before we assign the value of `$meta['post_date']` to `$args['post_date']`, so args gets the correct value for both `post_date` and `post_date_gmt`.

Comment (JayWood) [reply lib/import.php]: 😄 I paid zero attention that `$args` was used below, this is why I ❤️ code reviews!

Comment (JayWood) [reply lib/import.php]: 😄 completely ignored the fact `$args` was used below, will get that first thing in the am for ya - this is why I ❤️ code reviews!

**Comment by mAAdhaTTah** [comment]
Looks good! Merging now. Will cut a release to .org today or tomorrow.
